name: publish

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

  # Manually from actions tab
  workflow_dispatch:

  schedule:
    # Around 8am melbourne time in UTC
    - cron: "0 21 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
        with:
          cache-workspace-crates: true
      - run: cargo run -- ./feeds.txt ./out
      - uses: actions/upload-pages-artifact@v3
        with:
          path: ./out
      - uses: actions/deploy-pages@v4
